modLoader="javafml"
loaderVersion="[34,)"
license="Creative Commons Zero v1.0 Universal"
issueTrackerURL="https://github.com/LazrProductions/chessmod/issues"

[[mods]]
modId="chessmod"
version="1.1.3"
displayName="Chess mod"
updateJSONURL=""
displayURL=""
logoFile="chessmod.png"
authors="LazrProductions"
credits=""
description="Ever wanted to play chess in Minecraft? Well now you can, and checkers too! This mod adds chess pieces and a chess board to play chess in game!"

[[dependencies.chessmod]]
    modId="forge"
    mandatory=true
    versionRange="[41.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chessmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"